### ISSUE TITLE
local .sty file

### ISSUE THREAD

**Issue by fariza** [mbr/latex#6]
Hello 

Finally I am trying to use the compiler in my real code, and it doesn't work ;( the reason, is that I am including `\usepackage{emvadatasheet}` and I have the local `emvadatasheet.sty` in the same directory as the `document.tex` file.
If i compile using pdflatex it works, but it doesn't using your package.
I tried setting enviroment variables to include the directory but no luck so far.
Do you have any suggestions?

Thanks
Federico

**Comment by mbr** [comment]
Have you tried TEXINPUTS? ``build_pdf`` accepts a second parameter, which is a list and passed on as the TEXINPUT environment variable.

**Comment by fariza** [comment]
You're right, that works, sorry

One little thing, the exception is not really helpful, it doesn't point to the problem of pdflatex not finding the included file
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/latex/build.py", line 154, in build_pdf
    stdout=open(os.devnull, 'w'),
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pdflatex', '-interaction=batchmode', '-halt-on-error', '-no-shell-escape', '-file-line-error', '/tmp/tmpxak6e16y/tmpm4dcxox6.latex']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fariza/workspace/Scripts/temp/pdf.py", line 27, in <module>
    pdf = build_pdf(data)
  File "/usr/local/lib/python3.4/dist-packages/latex/build.py", line 202, in build_pdf
    return builder.build_pdf(source, texinputs)
  File "<string>", line 2, in build_pdf
  File "/usr/local/lib/python3.4/dist-packages/data/decorators.py", line 82, in _
    return f(*bvals.args, **bvals.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/latex/build.py", line 157, in build_pdf
    raise_from(LatexBuildError(base_fn + '.log'), e)
  File "/usr/local/lib/python3.4/dist-packages/future/utils/__init__.py", line 382, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
NameError: name 'CalledProcessError' is not defined
```

**Comment by mbr** [comment]
That  is a bug in ``future``, I *think*. A workaround is already in 0.5.5,
so you will get the correct exception with that one.
