### ISSUE TITLE
ImportError: cannot import name wraps (Python 2.7.6)

### ISSUE THREAD

**Issue by IARI** [mbr/latex#9]
when trying to do but this
```python
from latex import build_pdf
```
I get an import error.
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from latex import build_pdf
  File "/usr/local/lib/python2.7/dist-packages/latex/__init__.py", line 4, in <module>
    from .build import build_pdf
  File "/usr/local/lib/python2.7/dist-packages/latex/build.py", line 6, in <module>
    from data import Data as I
  File "/usr/local/lib/python2.7/dist-packages/data/__init__.py", line 9, in <module>
    from six import text_type, PY2, reraise, StringIO, BytesIO, Iterator, wraps
ImportError: cannot import name wraps
```
(Python 2.7.6, Ubuntu)

**Comment by IARI** [comment]
apparently I had an old version of the sixt package

    pip install six -U

fixxed it for me.
